//
//  TestElements.swift
//  MyShop
//
//  Created by Arash on 3/25/1396 AP.
//  Copyright © 1396 arashgood. All rights reserved.
//

import Foundation

var testbanners = [Product(url: "https://file.digikala.com/digikala/Image/Webstore/Banner/1396/3/13/f7ecbefe-a78e-4883-9d1d-912713fd876d.jpg", title: "title1", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.", price: 1000, id: 1, number: 1, availableNumber: 35),
                   Product(url: "https://www.google.com/imgres?imgurl=http%3A%2F%2Fwww.javanmobile.com%2Fwp-content%2Fuploads%2F2015%2F09%2FDigikala0.jpg&imgrefurl=http%3A%2F%2Fwww.javanmobile.com%2F34772%2Fdigikala-android%2F&docid=bUlK33fwltPHtM&tbnid=xxaAqYjhu8F1nM%3A&vet=10ahUKEwjPzYLi8KfZAhXNUlAKHZmtDNQQMwhdKCUwJQ..i&w=400&h=281&client=safari&bih=1379&biw=2560&q=digikala&ved=0ahUKEwjPzYLi8KfZAhXNUlAKHZmtDNQQMwhdKCUwJQ&iact=mrc&uact=8", title: "title2", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 2000, id: 12, number: 1,availableNumber: 25),
                   Product(url: "https://www.google.com/imgres?imgurl=http%3A%2F%2Fwww.javanmobile.com%2Fwp-content%2Fuploads%2F2015%2F09%2FDigikala0.jpg&imgrefurl=http%3A%2F%2Fwww.javanmobile.com%2F34772%2Fdigikala-android%2F&docid=bUlK33fwltPHtM&tbnid=xxaAqYjhu8F1nM%3A&vet=10ahUKEwjPzYLi8KfZAhXNUlAKHZmtDNQQMwhdKCUwJQ..i&w=400&h=281&client=safari&bih=1379&biw=2560&q=digikala&ved=0ahUKEwjPzYLi8KfZAhXNUlAKHZmtDNQQMwhdKCUwJQ&iact=mrc&uact=8", title: "title3", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 3000, id: 13, number: 1,availableNumber: 48),
                   Product(url: "https://www.google.com/imgres?imgurl=http%3A%2F%2Fwww.javanmobile.com%2Fwp-content%2Fuploads%2F2015%2F09%2FDigikala0.jpg&imgrefurl=http%3A%2F%2Fwww.javanmobile.com%2F34772%2Fdigikala-android%2F&docid=bUlK33fwltPHtM&tbnid=xxaAqYjhu8F1nM%3A&vet=10ahUKEwjPzYLi8KfZAhXNUlAKHZmtDNQQMwhdKCUwJQ..i&w=400&h=281&client=safari&bih=1379&biw=2560&q=digikala&ved=0ahUKEwjPzYLi8KfZAhXNUlAKHZmtDNQQMwhdKCUwJQ&iact=mrc&uact=8", title: "title4", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 4000, id: 14, number: 1,availableNumber: 120),
                   Product(url: "https://www.google.com/imgres?imgurl=https%3A%2F%2Ffile.digi-kala.com%2Fdigikala%2FImage%2FWebstore%2FProduct%2FP_49176%2FOriginal%2FMobile-Samsung-Galaxy-A55df920.jpg&imgrefurl=https%3A%2F%2Fwww.digikala.com%2FMain%2FMobile%2F&docid=PhNh4hG4zzOAeM&tbnid=QUJj806TopjPuM%3A&vet=10ahUKEwjPzYLi8KfZAhXNUlAKHZmtDNQQMwhmKC4wLg..i&w=1280&h=1280&client=safari&bih=1379&biw=2560&q=digikala&ved=0ahUKEwjPzYLi8KfZAhXNUlAKHZmtDNQQMwhmKC4wLg&iact=mrc&uact=8", title: "title5", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 3000, id: 11, number: 1,availableNumber: 240)]


var testProducts = [Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_104099/150/Computer-SSD-Samsung-850-Pro-256GBfcd394.jpg", title: "سامسونگ ۸۵۰ پروzzzzz", desc: "", price: 850000, id: 113, number: 1,availableNumber: 150),
                    Product(url: "https://www.google.com/imgres?imgurl=https%3A%2F%2Ffile.digi-kala.com%2Fdigikala%2FImage%2FWebstore%2FProduct%2FP_49176%2FOriginal%2FMobile-Samsung-Galaxy-A55df920.jpg&imgrefurl=https%3A%2F%2Fwww.digikala.com%2FMain%2FMobile%2F&docid=PhNh4hG4zzOAeM&tbnid=QUJj806TopjPuM%3A&vet=10ahUKEwjPzYLi8KfZAhXNUlAKHZmtDNQQMwhmKC4wLg..i&w=1280&h=1280&client=safari&bih=1379&biw=2560&q=digikala&ved=0ahUKEwjPzYLi8KfZAhXNUlAKHZmtDNQQMwhmKC4wLg&iact=mrc&uact=8", title: "شیایومی می بند ۲", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 200000, id: 199, number: 1,availableNumber: 1),
                    Product(url: "https://www.google.com/imgres?imgurl=http%3A%2F%2Fwww.javanmobile.com%2Fwp-content%2Fuploads%2F2015%2F09%2FDigikala0.jpg&imgrefurl=http%3A%2F%2Fwww.javanmobile.com%2F34772%2Fdigikala-android%2F&docid=bUlK33fwltPHtM&tbnid=xxaAqYjhu8F1nM%3A&vet=10ahUKEwjPzYLi8KfZAhXNUlAKHZmtDNQQMwhdKCUwJQ..i&w=400&h=281&client=safari&bih=1379&biw=2560&q=digikala&ved=0ahUKEwjPzYLi8KfZAhXNUlAKHZmtDNQQMwhdKCUwJQ&iact=mrc&uact=8", title: "اپل آیفون ۷", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 2800000, id: 12, number: 1,availableNumber: 200),
                    Product(url: "https://www.google.com/imgres?imgurl=https%3A%2F%2Ffile.digi-kala.com%2Fdigikala%2FImage%2FWebstore%2FProduct%2FP_354069%2F350%2FApple-iPhone-X-64GB-Mobile-Phone-1884e6.jpg&imgrefurl=https%3A%2F%2Fwww.digikala.com%2FProduct%2FDKP-354069%2F%25DA%25AF%25D9%2588%25D8%25B4%25D9%258A-%25D9%2585%25D9%2588%25D8%25A8%25D8%25A7%25D9%258A%25D9%2584-%25D8%25A7%25D9%25BE%25D9%2584-%25D9%2585%25D8%25AF%25D9%2584-iPhone-X-%25D8%25B8%25D8%25B1%25D9%2581%25D9%258A%25D8%25AA-64-%25DA%25AF%25D9%258A%25DA%25AF%25D8%25A7%25D8%25A8%25D8%25A7%25D9%258A%25D8%25AA&docid=GBn7CSTzG6TdRM&tbnid=WzQ_uVvwuHaGCM%3A&vet=10ahUKEwjPzYLi8KfZAhXNUlAKHZmtDNQQMwhvKDcwNw..i&w=350&h=350&client=safari&bih=1379&biw=2560&q=digikala&ved=0ahUKEwjPzYLi8KfZAhXNUlAKHZmtDNQQMwhvKDcwNw&iact=mrc&uact=8", title: "سامسونگ جی ۷", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 4000, id: 18, number: 1,availableNumber: 30),
                    Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_254080/150/Samsung-Galaxy-S8-Plus-SM-G955FD-Dual-SIM-Mobile-Phone-40bcfb.jpg", title: "سامسونگ گلکسی اس ۸", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 3000000, id: 17, number: 1,availableNumber: 1),
                    Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_210406/150/Fresh-Life-S5-Blood-Pressure-Monitor-03583a.jpg", title: "فشار سنج فرش لایف", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 1200000, id: 16, number: 1,availableNumber: 18),
                    
                    Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_20401/150/Hair-Clipper-Philips-AT890/204ddf65.jpg", title: "ریش تراش فیلیپس", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 1900000, id: 15, number: 1,availableNumber: 35),
                    Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_203451/150/Samsung-Gear-S3-Frontier-SM-R760-Smart-Watch-5c7b64.jpg", title: "ساعت هوشمند سامسونگ گیر", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 1200000, id: 1403, number: 1,availableNumber: 1),
                    Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_201873/150/Samsung-Gear-S3-Classic-SM-R770-Black-Leather-Smart-Watch-0fb40e.jpg", title: "ساعت هوشمند سامسونگ گیر", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 1200000, id: 13, number: 1,availableNumber: 159),
                    Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_210406/150/Fresh-Life-S5-Blood-Pressure-Monitor-03583a.jpg", title: "فشار سنج فرش لایف", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 1200000, id: 912, number: 1,availableNumber: 8),
                    Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_183989/150/Apple-iPhone-7-Plus-128GB-Mobile-Phone-2a7f67.jpg", title: "اپل آیفون ۷", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 2800000, id: 10, number: 1,availableNumber: 1),
                    Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_201979/150/Western-Digital-WDS240G1G0A-SSD-Drive---240GB-d7532e.jpg", title: "هارد دیسک وسترن دیجیتال ۲۴۰ گیگ", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 1200000, id: 111, number: 1,availableNumber: 1),
                    Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_161762/150/Computer-SSD-kingston-UV400-240GB.jpg", title: "هارد اس اس دی کینستون", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 1200000, id: 122, number: 1,availableNumber: 10),
                    Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_207283/150/Silicon-Cover-For-iPhone-6/6s-fb73f0.jpg", title: "کاور سیلیکونی آیفون ۶", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 1200000, id: 2, number: 1,availableNumber: 9),
                    Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_153949/150/Samsung-J7-(2016)-Mobile-Phone.jpg", title: "سامسونگ جی ۷", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 4000, id: 3, number: 1,availableNumber: 1),
                    
]

var testBasket = [Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_104099/150/Computer-SSD-Samsung-850-Pro-256GBfcd394.jpg", title: "zzzzzzسامسونگ ۸۵۰ پرو", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 850000, id: 199, number: 1,availableNumber: 1),
                  Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_180451/150/Xiaomi-Mi-Band-2-SmartBand.jpg", title: "شیایومی می بند ۲", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 200000, id: 19, number: 3,availableNumber: 3),
                  Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_183989/150/Apple-iPhone-7-Plus-128GB-Mobile-Phone-2a7f67.jpg", title: "اپل آیفون ۷", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 2800000, id: 10, number: 2,availableNumber: 1)
                  ]

let testOrders = [Order(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_207283/150/Silicon-Cover-For-iPhone-6/6s-fb73f0.jpg", title: "کاور سیلیکونی آیفون ۶", price: 1000, id: 1, number: 1, state: 1),
                  
                  Order(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_203451/150/Samsung-Gear-S3-Frontier-SM-R760-Smart-Watch-5c7b64.jpg", title: "ساعت هوشمند سامسونگ گیر", price: 1000000, id: 1, number: 1, state: 3),
                 
]

let testCategories = ["موبایل","پزشکی","ساعت","تجهیزات کامپیوتر","اکسسوری","بهداشتی","ورزشی","سرگرمی"]

var testLikedProducts = [Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_180451/150/Xiaomi-Mi-Band-2-SmartBand.jpg", title: "شیایومی می بند ۲", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 200000, id: 19, number: 1,availableNumber: 1),
                         Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_183989/150/Apple-iPhone-7-Plus-128GB-Mobile-Phone-2a7f67.jpg", title: "اپل آیفون ۷", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 2800000, id: 12, number: 1,availableNumber: 1),
                         Product(url: "https://file.digikala.com/Digikala/Image/Webstore/Product/P_153949/150/Samsung-J7-(2016)-Mobile-Phone.jpg", title: "سامسونگ جی ۷", desc: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.",price: 4000, id: 18, number: 1,availableNumber: 1)]









